version: "3.7"

services:
  server:
    image: dperson/samba:latest
    restart: always
    network_mode: host
    environment:
      - USERID=1000
      - GROUPID=1000
    volumes:
      - /home/umbrel/umbrel/home/PS2SMB:/share
    command: >
      -g "server min protocol = NT1"
      -g "server max protocol = NT1"
      -g "lanman auth = yes"
      -g "ntlm auth = yes"
      -g "map to guest = Bad User"
      -g "smb ports = 4445"
      -s "PS2SMB;/share;yes;no;yes;all;none;all;Umbrel PS2"
